### ISSUE TITLE
create index over a queried table

### ISSUE THREAD

**Issue by merlintang** [InitialDLab/Simba#73]
We are testing on the Simba. One natural application is here, we query a table and build index over the queried table. Then, execute the query over the indexed table. We are not sure whether this is supported in the Simba or not?  When we test this, it throw errors. Below are the testing code: 

    import simbaContext.implicits._
    import simbaContext.SimbaImplicits._
    var leftData = ListBuffer[PointData]()
    var rightData = ListBuffer[PointData]()

    for (i <- 1 to 1000){
      leftData += PointData( i + 0.0, i + 0.0, i + 0.0, "a = " + i)
      rightData += PointData(i + 0.0, i + 0.0, i + 0.0, "a = " + (i + 1))
    }

    val leftDF = sc.parallelize(leftData).toDF
    val rightDF = sc.parallelize(rightData).toDF

    leftDF.registerTempTable("point1")

    simbaContext.sql("SELECT * FROM point1 WHERE x < 10").registerTempTable("point2")

    simbaContext.indexTable("point2", RTreeType, "rt", Array("x", "y"))

    val newtable = simbaContext.table("point2")

    val df = newtable.knn(Array("x", "y"), Array(10.0, 10), 5)

    df.show()

The errors are: 
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: size=0 and step=0, but both must be positive
	at scala.collection.Iterator$GroupedIterator.<init>(Iterator.scala:866)
	at scala.collection.Iterator$class.grouped(Iterator.scala:1000)
	at scala.collection.AbstractIterator.grouped(Iterator.scala:1157)
	at scala.collection.IterableLike$class.grouped(IterableLike.scala:158)
	at scala.collection.mutable.ArrayOps$ofRef.grouped(ArrayOps.scala:108)
	at edu.utah.cs.simba.partitioner.STRPartitioner.edu$utah$cs$simba$partitioner$STRPartitioner$$recursiveGroupPoint$1(STRPartitioner.scala:109)
	at edu.utah.cs.simba.partitioner.STRPartitioner.<init>(STRPartitioner.scala:154)
	at edu.utah.cs.simba.partitioner.STRPartition$.apply(STRPartitioner.scala:49)
	at edu.utah.cs.simba.index.RTreeIndexedRelation.buildIndex(RTreeIndexedRelation.scala:72)
	at edu.utah.cs.simba.index.RTreeIndexedRelation.<init>(RTreeIndexedRelation.scala:58)
	at edu.utah.cs.simba.index.IndexedRelation$.apply(IndexedRelation.scala:41)
	at edu.utah.cs.simba.IndexManager$$anonfun$createIndexQuery$1.apply(IndexManager.scala:200)
	at edu.utah.cs.simba.IndexManager.writeLock(IndexManager.scala:63)
	at edu.utah.cs.simba.IndexManager.createIndexQuery(IndexManager.scala:191)
	at edu.utah.cs.simba.SimbaContext.indexTable(SimbaContext.scala:102)
	at edu.utah.cs.simba.examples.TestMain$.main(TestMain.scala:54)
	at edu.utah.cs.simba.examples.TestMain.main(TestMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
16/12/01 13:30:24 INFO SparkContext: Invoking stop() from shutdown hook

**Comment by gfl94** [comment]
Sure, Simba supports result reusage,  but there is a bug on our sampling strategy. 

We aimed at big data analysis, so our testing focus on big data process, the result table is usually not so large, which results in an empty sampled array. 

I will fix it right now.

**Comment by merlintang** [comment]
thanks for the hot fix, when this PR is merged, I will test it again.

**Comment by Skyprophet** [comment]
Merged, yet we will keep this ticket since there should be a better solution than this hot fix.

**Comment by merlintang** [comment]
It passed the test. close the ticket, but we need to have a better solution for this.
